# Generated by Django 5.1.4 on 2025-01-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superadmin',
            field=models.BooleanField(default=True),
        ),
    ]
