# Generated by Django 5.1.4 on 2025-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_customuser_managers_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_waiting_approval',
            field=models.BooleanField(default=False),
        ),
    ]
